---
# Source: template-application/templates/service.yml
apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: default
  labels:
    app: demo-app
spec:
  type: NodePort
  ports:
    - name: http
      port: 9999
      targetPort: 9999
      nodePort: 30000
  selector:
    app: demo-app
  sessionAffinity: None

---
# Source: template-application/templates/deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: demo-app
        version: v1.1.0-build.15
    spec:
      containers:
        - name: demo-app
          image: skikuta38/demo-app:v1.1.0-build.15
          imagePullPolicy: Always
          ports:
            - containerPort: 9999

